language: node_js
node_js:
  - "8.9.4"

language: node_js

env:
     - DB=postgresql://postgres@localhost:5432/users
node_js:
        - "8.9.4"

before_script:
  - psql -c 'create database  users;' -U postgres
  - psql -U postgres -d users -a -f table.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2